apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sentikenya

resources:
  - kafka-deployment.yaml
  - inference-deployment.yaml
  - inference-hpa.yaml

commonLabels:
  project: sentikenya
  environment: development
